name: CI & Production Deploy (Main)

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

  #      - name: Run Type Checks
  #        run: npm run typecheck
  #
  #      - name: Linting
  #        run: npm run lint

  deploy-production:
    name: Deploy Production Stack
    needs: test
    runs-on: host
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Deploy Self-Hosted Production Containers
        run: |
          echo "Deploying updated Docker containers to Production environment..."
          docker compose -f compose.dev.yaml down
          docker compose -f compose.prod.yaml down
          docker compose -f compose.prod.yaml up -d --build
