import { CourseList } from '@/components/CourseList';
import { CustomAppbarHeader } from '@/components/CustomAppbarHeader';
import { ScrollView } from '@expo/ui';
const courses = {
  time: '0.02s',
  list: [
    {
      code: '357269',
      name: '研究方法',
      credits: '1',
      type: '▲',
      prof: '林淑玲',
      sun: null,
      mons: null,
      tues: null,
      wed: '5 6 7',
      thu: null,
      fri: null,
      sat: null,
      classroom: '六教725(e)',
      ppl: 50,
      dropped_ppl: 0,
      lang: null,
      link: 'ShowSyllabus.jsp?snum=357269&code=11403',
      notes: '科研825',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357270',
      name: '企業倫理與永續管理',
      credits: '1',
      type: '▲',
      prof: '丁秀儀',
      sun: null,
      mons: '3 4',
      tues: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: '六教725(e)',
      ppl: 52,
      dropped_ppl: 0,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=357270&code=11710',
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '359389',
      name: '論文',
      credits: '2',
      type: '▲',
      prof: null,
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: null,
      ppl: 56,
      dropped_ppl: 0,
      lang: null,
      link: null,
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357153',
      name: '跨文化創造力與創業家策略',
      credits: '1',
      type: '★',
      prof: '劉宛淯',
      sun: null,
      mons: null,
      tues: '5 6 7',
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: '六教726(e)',
      ppl: 23,
      dropped_ppl: 0,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=357153&code=21405',
      notes: 'IMBA和資財所合開',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357163',
      name: '創業與籌資',
      credits: '1',
      type: '★',
      prof: '林冠仲',
      sun: null,
      mons: null,
      tues: null,
      wed: '2 3 4',
      thu: null,
      fri: null,
      sat: null,
      classroom: '六教226(e)',
      ppl: 29,
      dropped_ppl: 0,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=357163&code=24406',
      notes: 'IMBA和資財所合開',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '364817',
      name: '校外實務研究',
      credits: '1',
      type: '★',
      prof: null,
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: null,
      ppl: 2,
      dropped_ppl: 0,
      lang: null,
      link: null,
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '359572',
      name: '數位鑑識與調查',
      credits: '1',
      type: '★',
      prof: '林敬皇',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: null,
      fri: '5 6 7',
      sat: null,
      classroom: '科研大樓240e',
      ppl: 42,
      dropped_ppl: 1,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=359572&code=12391',
      notes: '資財所和創新資安合開',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357292',
      name: '個人資料保護與管理',
      credits: '1',
      type: '★',
      prof: '魏銪志',
      sun: null,
      mons: null,
      tues: '2 3 4',
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: '科研大樓240e',
      ppl: 36,
      dropped_ppl: 0,
      lang: null,
      link: 'ShowSyllabus.jsp?snum=357292&code=12148',
      notes: '資財所和創新資安合開',
      with_class: null,
      experiment: null,
      cross_disp: '資訊安全微學程',
    },
    {
      code: '357293',
      name: '資金管理',
      credits: '1',
      type: '★',
      prof: '吳牧恩',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: '2 3 4',
      fri: null,
      sat: null,
      classroom: '科研大樓825',
      ppl: 10,
      dropped_ppl: 0,
      lang: null,
      link: 'ShowSyllabus.jsp?snum=357293&code=11985',
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357295',
      name: '財務數值方法',
      credits: '1',
      type: '★',
      prof: '劉亮志',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: '5 6 7',
      fri: null,
      sat: null,
      classroom: '科研大樓240e',
      ppl: 17,
      dropped_ppl: 0,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=357295&code=11982',
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357300',
      name: '區塊鏈與數位資產',
      credits: '1',
      type: '★',
      prof: '黃朝秋\n鍾建屏',
      sun: null,
      mons: '5 6 7',
      tues: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: '科研哈佛講堂',
      ppl: 58,
      dropped_ppl: 0,
      lang: null,
      link: 'ShowSyllabus.jsp?snum=357300&code=24676',
      notes: '哈佛/資財四甲、資財所合開',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '359585',
      name: '公司治理',
      credits: '1',
      type: '★',
      prof: '陳鴻崑',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: '8 9 A',
      fri: null,
      sat: null,
      classroom: '六教226(e)',
      ppl: 6,
      dropped_ppl: 1,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=359585&code=12560',
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '359634',
      name: '金融創新與趨勢',
      credits: '1',
      type: '★',
      prof: '吳牧恩',
      sun: null,
      mons: null,
      tues: '6 7 8',
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: '科研大樓825',
      ppl: 15,
      dropped_ppl: 0,
      lang: null,
      link: 'ShowSyllabus.jsp?snum=359634&code=11985',
      notes: '科研823/資財四甲、資財所合開',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357302',
      name: '人工智慧開發與安全',
      credits: '1',
      type: '★',
      prof: '彭祖乙',
      sun: null,
      mons: '8 9 A',
      tues: null,
      wed: null,
      thu: null,
      fri: null,
      sat: null,
      classroom: '科研大樓243e',
      ppl: 42,
      dropped_ppl: 1,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=357302&code=12439',
      notes: '資財四甲、資財所和創新資安合開',
      with_class: null,
      experiment: null,
      cross_disp: '資訊安全微學程',
    },
    {
      code: '357303',
      name: '永續投資',
      credits: '1',
      type: '★',
      prof: '陳鴻崑',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: null,
      fri: '5 6 7',
      sat: null,
      classroom: '科研大樓825',
      ppl: 0,
      dropped_ppl: 0,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=357303&code=12560',
      notes: '1週【停開】',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '357304',
      name: '深度學習',
      credits: '1',
      type: '★',
      prof: '王貞淑',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: null,
      fri: '2 3 4',
      sat: null,
      classroom: '科研大樓240e',
      ppl: 25,
      dropped_ppl: 0,
      lang: null,
      link: 'ShowSyllabus.jsp?snum=357304&code=11505',
      notes: null,
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
    {
      code: '360023',
      name: '強化學習於財金應用',
      credits: '1',
      type: '★',
      prof: '張庭瑜',
      sun: null,
      mons: null,
      tues: null,
      wed: null,
      thu: null,
      fri: '8 9 A',
      sat: null,
      classroom: '科研大樓240e',
      ppl: 7,
      dropped_ppl: 1,
      lang: '英語',
      link: 'ShowSyllabus.jsp?snum=360023&code=12677',
      notes: '新聘專任教師',
      with_class: null,
      experiment: null,
      cross_disp: null,
    },
  ],
};
export default function Browse() {
  return (
    <>
      <CustomAppbarHeader title="Courses" />
      <ScrollView>
        <CourseList />
      </ScrollView>
      ;
    </>
  );
}
