import { useState } from "react";
import { useColorScheme } from "react-native";
import { Host, Row, Picker, Spacer, Text, Column, } from "@expo/ui";
  const mockDeps = {
    time: "0.62s",
    list: [
      {
        year: "115",
        sem: "1",
        code: "01",
        name: "教務處",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=01",
      },
      {
        year: "115",
        sem: "1",
        code: "10",
        name: "體育室",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=10",
      },
      {
        year: "115",
        sem: "1",
        code: "14",
        name: "通識中心",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=14",
      },
      {
        year: "115",
        sem: "1",
        code: "62",
        name: "師資培育中心",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=62",
      },
      {
        year: "115",
        sem: "1",
        code: "AA",
        name: "校院級課程",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=AA",
      },
      {
        year: "115",
        sem: "1",
        code: "2B",
        name: "智動科",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=2B",
      },
      {
        year: "115",
        sem: "1",
        code: "30",
        name: "機械系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=30",
      },
      {
        year: "115",
        sem: "1",
        code: "40",
        name: "機電所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=40",
      },
      {
        year: "115",
        sem: "1",
        code: "44",
        name: "車輛系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=44",
      },
      {
        year: "115",
        sem: "1",
        code: "45",
        name: "能源冷凍空調系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=45",
      },
      {
        year: "115",
        sem: "1",
        code: "56",
        name: "製科所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=56",
      },
      {
        year: "115",
        sem: "1",
        code: "61",
        name: "自動化所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=61",
      },
      {
        year: "115",
        sem: "1",
        code: "66",
        name: "機電科所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=66",
      },
      {
        year: "115",
        sem: "1",
        code: "81",
        name: "機電學士班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=81",
      },
      {
        year: "115",
        sem: "1",
        code: "A8",
        name: "機電科技博士外生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=A8",
      },
      {
        year: "115",
        sem: "1",
        code: "AG",
        name: "機械自動化外生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=AG",
      },
      {
        year: "115",
        sem: "1",
        code: "B2",
        name: "半導體學士學位學程",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=B2",
      },
      {
        year: "115",
        sem: "1",
        code: "B3",
        name: "半導體外生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=B3",
      },
      {
        year: "115",
        sem: "1",
        code: "C0",
        name: "機電學院",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=C0",
      },
      {
        year: "115",
        sem: "1",
        code: "32",
        name: "化工系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=32",
      },
      {
        year: "115",
        sem: "1",
        code: "33",
        name: "材資系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=33",
      },
      {
        year: "115",
        sem: "1",
        code: "34",
        name: "土木系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=34",
      },
      {
        year: "115",
        sem: "1",
        code: "35",
        name: "分子系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=35",
      },
      {
        year: "115",
        sem: "1",
        code: "42",
        name: "防災所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=42",
      },
      {
        year: "115",
        sem: "1",
        code: "51",
        name: "高分所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=51",
      },
      {
        year: "115",
        sem: "1",
        code: "60",
        name: "環境所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=60",
      },
      {
        year: "115",
        sem: "1",
        code: "68",
        name: "生化所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=68",
      },
      {
        year: "115",
        sem: "1",
        code: "73",
        name: "化工所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=73",
      },
      {
        year: "115",
        sem: "1",
        code: "78",
        name: "材料所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=78",
      },
      {
        year: "115",
        sem: "1",
        code: "79",
        name: "資源所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=79",
      },
      {
        year: "115",
        sem: "1",
        code: "83",
        name: "工程科技學士班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=83",
      },
      {
        year: "115",
        sem: "1",
        code: "A0",
        name: "能源光電外國學生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=A0",
      },
      {
        year: "115",
        sem: "1",
        code: "37",
        name: "工管系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=37",
      },
      {
        year: "115",
        sem: "1",
        code: "57",
        name: "經管系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=57",
      },
      {
        year: "115",
        sem: "1",
        code: "74",
        name: "管理所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=74",
      },
      {
        year: "115",
        sem: "1",
        code: "98",
        name: "管理外國學生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=98",
      },
      {
        year: "115",
        sem: "1",
        code: "AB",
        name: "資財系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=AB",
      },
      {
        year: "115",
        sem: "1",
        code: "C2",
        name: "管理學院",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=C2",
      },
      {
        year: "115",
        sem: "1",
        code: "38",
        name: "工設系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=38",
      },
      {
        year: "115",
        sem: "1",
        code: "39",
        name: "建築系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=39",
      },
      {
        year: "115",
        sem: "1",
        code: "52",
        name: "建都所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=52",
      },
      {
        year: "115",
        sem: "1",
        code: "58",
        name: "創新所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=58",
      },
      {
        year: "115",
        sem: "1",
        code: "84",
        name: "創意設計學士班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=84",
      },
      {
        year: "115",
        sem: "1",
        code: "85",
        name: "設計所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=85",
      },
      {
        year: "115",
        sem: "1",
        code: "AC",
        name: "互動系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=AC",
      },
      {
        year: "115",
        sem: "1",
        code: "AT",
        name: "互動與創新外生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=AT",
      },
      {
        year: "115",
        sem: "1",
        code: "49",
        name: "技職所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=49",
      },
      {
        year: "115",
        sem: "1",
        code: "54",
        name: "英文系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=54",
      },
      {
        year: "115",
        sem: "1",
        code: "91",
        name: "科技法律學程",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=91",
      },
      {
        year: "115",
        sem: "1",
        code: "A4",
        name: "智財所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=A4",
      },
      {
        year: "115",
        sem: "1",
        code: "A5",
        name: "文發系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=A5",
      },
      {
        year: "115",
        sem: "1",
        code: "31",
        name: "電機系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=31",
      },
      {
        year: "115",
        sem: "1",
        code: "36",
        name: "電子系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=36",
      },
      {
        year: "115",
        sem: "1",
        code: "59",
        name: "資工系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=59",
      },
      {
        year: "115",
        sem: "1",
        code: "65",
        name: "光電系",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=65",
      },
      {
        year: "115",
        sem: "1",
        code: "82",
        name: "電資學士班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=82",
      },
      {
        year: "115",
        sem: "1",
        code: "99",
        name: "電資外國學生專班",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=99",
      },
      {
        year: "115",
        sem: "1",
        code: "AY",
        name: "太空所",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=AY",
      },
      {
        year: "115",
        sem: "1",
        code: "C5",
        name: "電資學院",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=C5",
      },
      {
        year: "115",
        sem: "1",
        code: "C7",
        name: "創新學院",
        link: "Subj.jsp?format=-3&year=115&sem=1&code=C7",
      },
    ],
  };
  import { Platform } from "react-native";
const FLAVOURS = [
  { label: "Vanilla", value: "vanilla" },
  { label: "Chocolate", value: "chocolate" },
  { label: "Strawberry", value: "strawberry" },
];

export default function PickerMenuExample() {
  const [value, setValue] = useState("AY");
  const colorScheme = useColorScheme();

  return (
    <Host matchContents={{ vertical: true }} style={{ width: "100%" }}>
    
          <Picker
           
            selectedValue={value}
            onValueChange={setValue}
          >
            {mockDeps.list.map((f) => (
              <Picker.Item key={f.code} label={f.name} value={f.code} />
            ))}
          </Picker>
    </Host>
  );
}
